language: python
python:
  - "3.5"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
before_script:
  - nvm install 0.12
  - node --version
  - npm --version
  - nvm --version
  - npm install
script:
  - npm build
  - npm test
after_success:
  - cat ./coverage/lcov.info | ./node_modules/.bin/coveralls
addons:
  firefox: latest